<a href="https://colab.research.google.com/github/safuh/safuh/blob/main/tf_selfpaced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div class="markdown-google-sans">
  <h1>Self paced Tensorflow learning</h1>
</div>


Set up tensorflow and load dataset

In [22]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist
(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

<div class="markdown-google-sans">
Build a model
</div>
Build a tf.keras.Sequential model and stack layers.

In [23]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


For each example, the model returns a vector of logits or log-odds scores, one for each class.

In [24]:
predictions = model(x_train[:1]).numpy()
predictions


array([[ 0.10144088,  0.29887864,  0.56690294,  0.30080888, -0.24883653,
         0.99122053,  0.18735993, -0.46062946,  0.60445786,  0.01536659]],
      dtype=float32)

The tf.nn.softmax function converts these logits to probabilities for each class: 

In [25]:
tf.nn.softmax(predictions).numpy()


array([[0.08063398, 0.09823454, 0.12842977, 0.09842434, 0.05680605,
        0.19631094, 0.08786831, 0.0459636 , 0.13334465, 0.07398378]],
      dtype=float32)

Define a loss function for training using losses.SparseCategoricalCrossentropy, which takes a vector of logits and a True index and returns a scalar loss for each example.

In [26]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.

In [27]:
loss_fn(y_train[:1], predictions).numpy()


1.6280555

Before you start training, configure and compile the model using Keras Model.compile. Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [28]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


Train and evaluate model.

In [29]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2938 - accuracy: 0.9168
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1454 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1084 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0882 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0770 - accuracy: 0.9765


Use Model.evaluate to check model performance on test set

In [30]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 1s - loss: 0.0834 - accuracy: 0.9757 - 546ms/epoch - 2ms/step


[0.08344067633152008, 0.9757000207901001]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [31]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])



<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.0659761e-09, 6.7103345e-09, 4.7963758e-06, 1.2340789e-05,
        2.4218735e-12, 1.8156037e-07, 9.4378823e-14, 9.9998212e-01,
        1.3514415e-07, 2.8698884e-07],
       [7.8711508e-09, 2.8690085e-04, 9.9953008e-01, 1.7696009e-04,
        4.2320948e-14, 4.7100420e-06, 2.2522604e-08, 3.4188017e-13,
        1.3353700e-06, 4.0833735e-13],
       [9.3940534e-06, 9.9358153e-01, 2.3041328e-03, 1.3520775e-04,
        9.9736462e-05, 2.1082345e-05, 5.5421937e-05, 3.2269899e-03,
        5.6519214e-04, 1.3785477e-06],
       [9.9993765e-01, 1.6619415e-08, 8.7804510e-06, 3.3824497e-07,
        4.2339346e-10, 4.6652772e-06, 9.1538988e-07, 3.5554149e-05,
        1.6784868e-09, 1.2129381e-05],
       [2.7970588e-08, 4.0662517e-08, 8.1722601e-06, 1.0969565e-07,
        9.9920541e-01, 4.8241287e-07, 9.4199486e-06, 2.6748664e-04,
        9.2999665e-07, 5.0795905e-04]], dtype=float32)>

Happy Coding!